
obj-$(CONFIG_HCC_HOTPLUG) += hotplug/
obj-$(CONFIG_HCC_CAP) += capability/
obj-$(CONFIG_HCC_PROCFS) += procfs/
obj-$(CONFIG_HCC_PROC) += proc/
obj-$(CONFIG_HCC_DVFS) += fs/
obj-$(CONFIG_HCC_EPM) += epm/ ghost/
obj-$(CONFIG_HCC_MM) += mm/
obj-$(CONFIG_HCC_SCHED) += scheduler/
