obj-$(CONFIG_HCC_SCHED_CPU_PROBE) += cpu_probe.o
obj-$(CONFIG_HCC_SCHED_MEM_PROBE) += mem_probe.o

obj-$(CONFIG_HCC_SCHED_MIGRATION_PROBE) += migration_probe.o
obj-$(CONFIG_HCC_SCHED_MOSIX_PROBE) += mosix_probe.o

EXTRA_CFLAGS += -Werror -Wall
