#ifndef __HCCSYMS__
#define __HCCSYMS__

#ifndef __ASSEMBLY__

typedef enum hccsyms_val {
	HCCSYMS_UNDEF, // Must be the first one
	HCCSYMS_VM_OPS_NULL,
	HCCSYMS_VM_OPS_SHM,
	HCCSYMS_VM_OPS_SHMEM,
	HCCSYMS_VM_OPS_FILE_GENERIC,
	HCCSYMS_VM_OPS_FILE_EXT4,
	HCCSYMS_VM_OPS_NFS_FILE,
	HCCSYMS_VM_OPS_OCFS2_FILE,
	HCCSYMS_VM_OPS_SPECIAL_MAPPING,
	HCCSYMS_VM_OPS_MEMORY_GDM_VMOPS,
	HCCSYMS_ARCH_UNMAP_AREA,
	HCCSYMS_ARCH_UNMAP_AREA_TOPDOWN,
	HCCSYMS_ARCH_GET_UNMAP_AREA,
	HCCSYMS_ARCH_GET_UNMAP_AREA_TOPDOWN,
	HCCSYMS_ARCH_GET_UNMAP_EXEC_AREA,

	/* Bin format structures */
	HCCSYMS_BINFMTS_AOUT,
	HCCSYMS_BINFMTS_ELF,
	HCCSYMS_BINFMTS_ELF_FDPIC,
	HCCSYMS_BINFMTS_EM86,
	HCCSYMS_BINFMTS_FLAT,
	HCCSYMS_BINFMTS_MISC,
	HCCSYMS_BINFMTS_SCRIPT,
	HCCSYMS_BINFMTS_SOM,
	HCCSYMS_BINFMTS_ARCH,

	/* Restart block functions */
	HCCSYMS_DO_NO_RESTART_SYSCALL,
	HCCSYMS_COMPAT_NANOSLEEP_RESTART,
	HCCSYMS_COMPAT_CLOCK_NANOSLEEP_RESTART,
	HCCSYMS_HRTIMER_NANOSLEEP_RESTART,
	HCCSYMS_POSIX_CPU_NSLEEP_RESTART,
	HCCSYMS_DO_RESTART_POLL,
	HCCSYMS_FUTEX_WAIT_RESTART,

	/* GDM set operations */
	HCCSYMS_GDM_TREE_OPS,
	HCCSYMS_GDM_PT_OPS,

	/* DVFS mobility operations */
	HCCSYMS_DVFS_MOBILITY_FAF_OPS,
	HCCSYMS_DVFS_MOBILITY_REGULAR_OPS,

	HCCSYMS_TABLE_SIZE // Must be the last one
} hccsyms_val_t;

int hccsyms_register(enum hccsyms_val v, void* p);
int hccsyms_unregister(enum hccsyms_val v);

enum hccsyms_val hccsyms_export(void* p);
void* hccsyms_import(enum hccsyms_val v);

extern int init_hccsyms(void);

#endif /* __ASSEMBLY__ */

#endif /* __HCCSYMS__ */
